### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-automated-upcoming-event-notifications#10]
## Issue Overview

Josh nor I are aware why this hasn't been released, but it hasn't. It seems like a useful feature add-on. 

Release tasks:

* [x] Ping the team to confirm if anyone is aware this wasnt released -> Josh said the only reason was because "no one released it"
* [ ] Double-check code is still all ready for release
* [ ] Re-test
* [ ] p2 release post (like http://p2.eventespresso.com/2019/06/10/importer-add-on-launch-checklist/) and all those steps involved

**Comment by mnelson4** [comment]
I haven't been assigned by anyone to work on this, I'm just seeing a need and trying to fill it; it's a-ok to pass to someone else who's more familiar with this add-on.

**Comment by mnelson4** [comment]
Upon further consideration, it seems the dependence on `WP_Cron` was what held this up. With many shared hosts, it's just not working reliably. 

IMO it sounds like we should notify potential buyers of that hard requirement (that `WP_Cron` is working, and that the site health tools is reporting that it's working), and document it, then it seems reasonable to proceed with preparing it for release.

**Comment by lorenzocaum** [comment]
Hey Mike, I'm starting pre-launch tasks for the new extension.

Is this set up with Grunt?

I think it is as I see "Bumping version to..." in the commit message but I want to double-check.

**Comment by joshfeck** [comment]
> IMO it sounds like we should notify potential buyers of that hard requirement (that WP_Cron is working, and that the site health tools is reporting that it's working), and document it, then it seems reasonable to proceed with preparing it for release.

I agree. One other thing to point out is, in most cases, emails are not going to be sent out when they're expected to even if wp_cron is working as expected. This is because wp_cron isn't a real cron and gets triggered only when the site gets traffic. So some reasonable expectations need to be set and it would be good to have some documentation for how to get started with adding a real cron job.

**Comment by joshfeck** [comment]
> Is this set up with Grunt?

Yes.

**Comment by mnelson4** [comment]
>  it would be good to have some documentation for how to get started with adding a real cron job.

+1. Usually the documentation would depend on the hosting company, but here's siteground's tutorial on how to do that: https://www.siteground.com/tutorials/wordpress/real-cron-job/

Also, linking to some tutorials on how to improve WordPress email delivery may be appropriate (eg https://betternotificationsforwp.com/documentation/getting-started/how-to-improve-email-delivery/)

**Comment by lorenzocaum** [comment]
@joshfeck Could you please run a release build for the automated upcoming event notifications add-on and share here?

Thanks

**Comment by joshfeck** [comment]
You'll find the link to download the archive in the buildnotifications Slack channel.

**Comment by lorenzocaum** [comment]
**Pre-launch notes**

With the Automated Upcoming Event Notifications add-on, your attendees, registrants, and participants will receive event reminders through email a day before the event. Customize the email notification to go out (e.g., remind 2 or 3 days before) depending on your needs.

**GitHub slug**: eea-automated-upcoming-event-notifications

**Recurly plan code**: eea_automated_upcoming_event_notifications+yearly
**Product page slug**: eea-automated-upcoming-event-notifications

**Recurly Event Espresso live:** https://eventespresso.recurly.com/plans/eea_automated_upcoming_event_notifications +yearly
**Recurly Event Espresso staging:** https://stagingeecom.recurly.com/plans/eea_automated_upcoming_event_notifications +yearly

**Event Espresso live product page**: 
- https://docs.google.com/document/d/1K4mUStQfny_IvWSFWwKN1fR2phl60IgJFF1Ncs_wG-0/edit#heading=h.ftntm6z0f0xf 
- https://eventespresso.com/?post_type=pues2custom_pricing&p=300365&preview=true 
- https://eventespresso.com/product/eea-automated-upcoming-event-notifications/

**Documentation page**: 
- https://docs.google.com/document/d/1vyLyLbhcc7IaGdw5gMDkMxnJW_SSdwLA8XD4JQd_tt4/edit - https://eventespresso.com/?post_type=wpwtds_article&p=300356&preview=true
- https://eventespresso.com/wiki/eea-automated-upcoming-event-notifications/

**Trello card**: https://trello.com/c/KidIOnz5/
**P2**:

**Comment by garthkoyle** [comment]
Did you intend to use the quotation marks in the content to describe the uses? That doesn't seem quite right unless you are quoting someone:
![image](https://user-images.githubusercontent.com/3094547/66494263-9b0df580-ea74-11e9-9d4a-4becd3f8decb.png)

**Comment by joshfeck** [comment]
> Remind attendees the evening before a beach party

You might want to avoid mentioning the possibility of scheduling an "evening before" reminder because the the UI only allows x days before. So for example if the "beach party" starts at noon, then realistically the latest the email could be scheduled would be around noon the day before.

**Comment by lorenzocaum** [comment]
They are quotes from customer conversations except for the middle one about festivals. I added that one.

Here is an example of an original that I edited:

On the day before the specific workshop, I want the system to send a reminder to all attendees (automatically).

Thanks for the heads up about the timing. I updated that one to this:

Remind attendees the day before an evening beach party.

**Comment by garthkoyle** [comment]
If those are quotes, then you might change the sentence before the list items:

From:
> Here are a few ways that our event organizers use the Automated Upcoming Event Notifications extension for their events:

to:

> Here are a few ways that our event organizers describe using the Automated Upcoming Event Notifications extension for their events:

**Comment by lorenzocaum** [comment]
http://p2.eventespresso.com/2019/10/07/this-week-in-event-espresso-october-6-october-12/#comment-20389
