### ISSUE TITLE
Remove Google+ from Registrant email notifications

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-automated-upcoming-event-notifications#11]
![Image 2019-10-10 at 2 46 42 PM](https://user-images.githubusercontent.com/1079138/66597431-f9b69a80-eb6c-11e9-8918-62fdc0aeb3bc.png)

![Image 2019-10-10 at 2 46 19 PM](https://user-images.githubusercontent.com/1079138/66597443-fd4a2180-eb6c-11e9-8c60-2869eea05d29.png)

The buttons also have extra spacing at the top as the link text is on its own line:

![Image 2019-10-10 at 2 50 01 PM](https://user-images.githubusercontent.com/1079138/66597697-82353b00-eb6d-11e9-9ddb-f924332b6747.png)

**Comment by sethshoultes** [comment]
@joshfeck who would be a good candidate to remove this?
