### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-automated-upcoming-event-notifications#8]
## Issue Overview

There have been unit test failures for a while now: https://travis-ci.com/eventespresso/eea-automated-upcoming-event-notifications/jobs/218461569. Strangely though, that error doesn't happen for all versions of PHP

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 4.9.x and 4.10.x

Version of this addon: master

Version of WordPress: latest I think, and 4.5

PHP Version:  5.6, although I'm reproducing locally on 7.1

Browser used:  n/a

## Steps to Reproduce (for bugs)

Run the unit tests locally for this add-on, with either EE master or a 4.9.x branch. I'm getting that fatal error.

**Comment by mnelson4** [comment]
Actually that failure is kinda the tip of the iceberg. I fixed it quickly by adding `require_once(EE_AUTOMATED_UPCOMING_EVENT_PLUGIN_DIR . 'domain/services/messages/EE_Specific_Datetime_Shortcodes.lib.php');` to the start of `\EventEspresso\AutomateUpcomingEventNotificationsTests\mocks\SpecificDatetimeShortcodesMock`, but then a ton more failures got reported. 
I see Brent, Josh, and Seth have been more involved in this add-on's development, but I'm ok with getting familiarized with it through debugging this issue.

**Comment by joshfeck** [comment]
The fails should be fixed and wrt the Automated Event Notifcations plugin, we want to require WP 5.2 because of the Site Health tools it adds. We also want to require PHP 7 for any **new** add-ons to help encourage best practices. So any unit tests against older versions of WP and older versions of PHP could be removed.

**Comment by mnelson4** [comment]
Great context thanks

**Comment by mnelson4** [comment]
PR merged. Now just watching unit tests to confirm master is ok.

**Comment by mnelson4** [comment]
Yep, I manually triggered a build on Travis (it didn't automatically when I merged the PR to master, which was weird), and it worked: https://travis-ci.com/eventespresso/eea-automated-upcoming-event-notifications/builds/120765445
